"use client";
import html2pdf from "html2pdf.js";
export interface ReportSection {
  title: string;
  headers: string[];
  rows: Array<Array<string | number | null | undefined>>;
}

const REPORT_FOOTER_LINES = [
  "Generated by Zeeve Platform • All Rights Reserved © 2026",
  "This report contains confidential information about your blockchain infrastructure",
];

const normalizeValue = (value: string | number | null | undefined) => {
  if (value === null || value === undefined) {
    return "NA";
  }
  return String(value);
};

const escapeCsvValue = (value: string) => {
  if (value.includes("\n") || value.includes(",") || value.includes('"')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
};

const buildCsv = (sections: ReportSection[]) => {
  const lines: string[] = [];
  sections.forEach((section) => {
    lines.push(escapeCsvValue(section.title));
    lines.push(section.headers.map((header) => escapeCsvValue(header)).join(","));
    section.rows.forEach((row) => {
      const cells = row.map((cell) => escapeCsvValue(normalizeValue(cell)));
      lines.push(cells.join(","));
    });
    lines.push("");
  });

  REPORT_FOOTER_LINES.forEach((footerLine) => {
    lines.push(escapeCsvValue(footerLine));
  });

  return lines.join("\n");
};

const buildHtml = (title: string, sections: ReportSection[]) => {
  const sectionMarkup = sections
    .map((section) => {
      const rowsMarkup = section.rows
        .map((row) => {
          const cells = row
            .map(
              (cell) => `<td style="padding:8px 10px; border-bottom:1px solid #e2e8f0;">${normalizeValue(cell)}</td>`,
            )
            .join("");
          return `<tr>${cells}</tr>`;
        })
        .join("");

      const headerMarkup = section.headers
        .map(
          (header) => `<th style="text-align:left; padding:8px 10px; border-bottom:2px solid #cbd5f5;">${header}</th>`,
        )
        .join("");

      return `
        <section style="margin-bottom:24px;">
          <h2 style="margin:0 0 8px 0; font-size:18px; color:#0f172a;">${section.title}</h2>
          <table style="width:100%; border-collapse:collapse; font-size:14px; color:#334155;">
            <thead><tr>${headerMarkup}</tr></thead>
            <tbody>${rowsMarkup}</tbody>
          </table>
        </section>
      `;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
</head>
<body style="font-family: 'DM Sans', Arial, sans-serif; background:#f8fafc; margin:0; padding:24px;">
  <div style="max-width:900px; margin:0 auto; background:#ffffff; border-radius:16px; padding:24px; box-shadow:0 12px 30px rgba(15, 23, 42, 0.12);">
    <h1 style="margin:0 0 20px 0; font-size:24px; color:#0b1220;">${title}</h1>
    ${sectionMarkup}
    <div style="border-top:1px solid #e8e8e8; padding-top:12px; margin-top:24px; font-size:10px; color:#999; text-align:center;">
      <p style="margin:0 0 6px 0;">${REPORT_FOOTER_LINES[0]}</p>
      <p style="margin:0;">${REPORT_FOOTER_LINES[1]}</p>
    </div>
  </div>
</body>
</html>`;
};

const triggerDownload = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const downloadCsvReport = (filename: string, sections: ReportSection[]) => {
  const csv = buildCsv(sections);
  triggerDownload(new Blob([csv], { type: "text/csv;charset=utf-8;" }), filename);
};

const downloadHtmlReport = (filename: string, title: string, sections: ReportSection[]) => {
  const html = buildHtml(title, sections);
  triggerDownload(new Blob([html], { type: "text/html;charset=utf-8;" }), filename);
};

const downloadPdfReport = async (
  filename: string,
  title: string,
  sections: Array<{
    title: string;
    headers: string[];
    rows: Array<Array<string | number>>;
  }>,
): Promise<void> => {
  // Yield to browser to update UI
  await new Promise((resolve) => {
    setTimeout(resolve, 300);
  });

  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const html = `
    <html>
      <head>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            color: #1a1a1a;
          }
          .container {
            max-width: 210mm;
            margin: 0 auto;
            background: white;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
            border-bottom: 4px solid #764ba2;
            position: relative;
            overflow: hidden;
          }
          .header::before {
            content: '';
            position: absolute;
            top: -50%;
            right: -10%;
            width: 300px;
            height: 300px;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 50%;
          }
          .header-content {
            position: relative;
            z-index: 1;
          }
          .header h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
          }
          .header-meta {
            font-size: 12px;
            opacity: 0.95;
            display: flex;
            gap: 20px;
            margin-top: 12px;
          }
          .header-divider {
            width: 40px;
            height: 3px;
            background: rgba(255, 255, 255, 0.6);
            margin-top: 12px;
          }
          .content {
            padding: 24px;
          }
          .section {
            margin-bottom: 24px;
            page-break-inside: avoid;
          }
          .section:last-child {
            margin-bottom: 0;
          }
          .section-title {
            font-size: 14px;
            font-weight: 700;
            color: #667eea;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 16px;
            padding-bottom: 8px;
            border-bottom: 2px solid #e8e8e8;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
          }
          thead {
            background: linear-gradient(90deg, #f5f7fa 0%, #eff2f5 100%);
          }
          th {
            padding: 12px 10px;
            text-align: left;
            font-weight: 600;
            color: #667eea;
            border-bottom: 2px solid #667eea;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          td {
            padding: 10px;
            border-bottom: 1px solid #e8e8e8;
            color: #333;
          }
          tbody tr {
            transition: background-color 0.2s;
          }
          tbody tr:nth-child(odd) {
            background-color: #f9f9fb;
          }
          tbody tr:nth-child(even) {
            background-color: #ffffff;
          }
          tbody tr:hover {
            background-color: #f0f2ff;
          }
          .footer {
            border-top: 1px solid #e8e8e8;
            padding-top: 12px;
            margin-top: 24px;
            font-size: 10px;
            color: #999;
            text-align: center;
          }
          .status-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
          }
          .status-good {
            background-color: #d4edda;
            color: #155724;
          }
          .status-warning {
            background-color: #fff3cd;
            color: #856404;
          }
          .status-critical {
            background-color: #f8d7da;
            color: #721c24;
          }
          @media print {
            body {
              background: white;
            }
            .container {
              box-shadow: none;
              margin: 0;
            }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="header-content">
              <h1>${title}</h1>
              <div class="header-divider"></div>
              <div class="header-meta">
                <span>📅 ${currentDate}</span>
                <span>🔗 Blockchain Node Report</span>
              </div>
            </div>
          </div>
          <div class="content">
            ${sections
              .map(
                (section) => `
              <div class="section">
                <div class="section-title">${section.title}</div>
                <table>
                  <thead>
                    <tr>
                      ${section.headers.map((header) => `<th>${header}</th>`).join("")}
                    </tr>
                  </thead>
                  <tbody>
                    ${section.rows
                      .map(
                        (row) => `
                      <tr>
                        ${row.map((cell) => `<td>${cell}</td>`).join("")}
                      </tr>
                    `,
                      )
                      .join("")}
                  </tbody>
                </table>
              </div>
            `,
              )
              .join("")}
            <div class="footer">
              <p>Generated by Zeeve Platform • All Rights Reserved © 2026</p>
              <p>This report contains confidential information about your blockchain infrastructure</p>
            </div>
          </div>
        </div>
      </body>
    </html>
  `;

  const element = document.createElement("div");
  element.innerHTML = html;

  const options = {
    margin: [10, 10, 10, 10] as [number, number, number, number],
    filename: filename,
    image: { type: "png" as const, quality: 0.98 },
    html2canvas: { scale: 2, logging: false, useCORS: true },
    jsPDF: { orientation: "portrait" as const, unit: "mm" as const, format: "a4", compress: true },
    pagebreak: { mode: ["avoid-all", "css", "legacy"] },
  };

  return new Promise<void>((resolve) => {
    html2pdf()
      .set(options)
      .from(element)
      .save()
      .then(() => {
        resolve();
      });
  });
};

export { downloadCsvReport, downloadHtmlReport, downloadPdfReport };
