FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps

RUN apk add --no-cache libc6-compat 
WORKDIR /app
ARG GITLAB_ACCESS_TOKEN
COPY ./package*.json ./
COPY ./.npmrc ./

RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# NEXT_PUBLIC_BASE_PATH="/platform"
ARG NEXT_PUBLIC_BASE_PATH
# NEXT_PUBLIC_HOST="app.develop.zeeve.io" | "app.staging.zeeve.io" | "app.zeeve.io"
ARG NEXT_PUBLIC_HOST
ARG NEXT_PUBLIC_IFRAME_ORIGIN
ARG NEXT_PUBLIC_IFRAME_SCRIPT_ORIGIN
ARG NEXT_PUBLIC_VIZION_BACKEND
# NEXT_PUBLIC_ENVIRONMENT="prod" | "stage" | "dev" | "local"
ARG NEXT_PUBLIC_ENVIRONMENT
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SALESIQ_WIDGET_URL
# NEXT_PUBLIC_ENABLE_RECAPTCHA="true" | "false"
ARG NEXT_PUBLIC_ENABLE_RECAPTCHA
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG ZOHO_DESK_BASE_URL
ARG ZOHO_DESK_ORG_ID
ARG ZOHO_DESK_DEPARTMENT_ID
ARG ZOHO_DESK_ACCESS_TOKEN
ARG ZOHO_DESK_REFRESH_TOKEN
ARG ZOHO_DESK_CLIENT_ID
ARG ZOHO_DESK_CLIENT_SECRET
ARG ZOHO_ACCOUNTS_BASE_URL
ARG NEXT_PUBLIC_NODE_METRICS_BEARER_TOKEN
ARG NEXT_PUBLIC_ZKSYNC_DEMO_SERVICE_ID
ARG NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_TOKEN
ARG NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_HOST_ID
ARG NPM_TOKEN

ENV NEXT_PUBLIC_BASE_PATH $NEXT_PUBLIC_BASE_PATH
ENV NEXT_PUBLIC_HOST $NEXT_PUBLIC_HOST
ENV NEXT_PUBLIC_ENVIRONMENT $NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_IFRAME_ORIGIN $NEXT_PUBLIC_IFRAME_ORIGIN
ENV NEXT_PUBLIC_IFRAME_SCRIPT_ORIGIN $NEXT_PUBLIC_IFRAME_SCRIPT_ORIGIN
ENV NEXT_PUBLIC_VIZION_BACKEND $NEXT_PUBLIC_VIZION_BACKEND
ENV NEXT_PUBLIC_API_URL $NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SALESIQ_WIDGET_URL $NEXT_PUBLIC_SALESIQ_WIDGET_URL
ENV NEXT_PUBLIC_ENABLE_RECAPTCHA $NEXT_PUBLIC_ENABLE_RECAPTCHA
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY $NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV ZOHO_DESK_BASE_URL $ZOHO_DESK_BASE_URL
ENV ZOHO_DESK_ORG_ID $ZOHO_DESK_ORG_ID
ENV ZOHO_DESK_DEPARTMENT_ID $ZOHO_DESK_DEPARTMENT_ID
ENV ZOHO_DESK_ACCESS_TOKEN $ZOHO_DESK_ACCESS_TOKEN
ENV ZOHO_DESK_REFRESH_TOKEN $ZOHO_DESK_REFRESH_TOKEN
ENV ZOHO_DESK_CLIENT_ID $ZOHO_DESK_CLIENT_ID
ENV ZOHO_DESK_CLIENT_SECRET $ZOHO_DESK_CLIENT_SECRET
ENV ZOHO_ACCOUNTS_BASE_URL $ZOHO_ACCOUNTS_BASE_URL
ENV NEXT_PUBLIC_NODE_METRICS_BEARER_TOKEN $NEXT_PUBLIC_NODE_METRICS_BEARER_TOKEN
ENV NEXT_PUBLIC_ZKSYNC_DEMO_SERVICE_ID $NEXT_PUBLIC_ZKSYNC_DEMO_SERVICE_ID
ENV NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_TOKEN $NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_TOKEN
ENV NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_HOST_ID $NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_HOST_ID
ENV NPM_TOKEN $NPM_TOKEN

RUN npm i sharp
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner

WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT 3000

CMD ["node", "server.js"]
