const DEFAULT_ARBITRUM_DEMO_SERVICE_ID = "abc";

const ARBITRUM_DEMO_SERVICE_ID =
  process.env.NEXT_PUBLIC_ARBITRUM_DEMO_SERVICE_ID?.trim() || DEFAULT_ARBITRUM_DEMO_SERVICE_ID;

const ARBITRUM_DEMO_VIZION_TOKEN = process.env.NEXT_PUBLIC_ARBITRUM_DEMO_VIZION_TOKEN?.trim() || "";
const ARBITRUM_DEMO_VIZION_HOST_ID = process.env.NEXT_PUBLIC_ARBITRUM_DEMO_VIZION_HOST_ID?.trim() || "10837";

export {
  DEFAULT_ARBITRUM_DEMO_SERVICE_ID,
  ARBITRUM_DEMO_SERVICE_ID,
  ARBITRUM_DEMO_VIZION_TOKEN,
  ARBITRUM_DEMO_VIZION_HOST_ID,
};
