const DEFAULT_OPSTACK_DEMO_SERVICE_ID = "abc";

const OPSTACK_DEMO_SERVICE_ID =
  process.env.NEXT_PUBLIC_OPSTACK_DEMO_SERVICE_ID?.trim() || DEFAULT_OPSTACK_DEMO_SERVICE_ID;

const OPSTACK_DEMO_VIZION_TOKEN = process.env.NEXT_PUBLIC_OPSTACK_DEMO_VIZION_TOKEN?.trim() || "";
const OPSTACK_DEMO_VIZION_HOST_ID = process.env.NEXT_PUBLIC_OPSTACK_DEMO_VIZION_HOST_ID?.trim() || "10796";

export {
  DEFAULT_OPSTACK_DEMO_SERVICE_ID,
  OPSTACK_DEMO_SERVICE_ID,
  OPSTACK_DEMO_VIZION_TOKEN,
  OPSTACK_DEMO_VIZION_HOST_ID,
};
