const DEFAULT_POLYGON_CDK_DEMO_SERVICE_ID = "";

const POLYGON_CDK_DEMO_SERVICE_ID =
  process.env.NEXT_PUBLIC_POLYGON_CDK_DEMO_SERVICE_ID?.trim() || DEFAULT_POLYGON_CDK_DEMO_SERVICE_ID;

const POLYGON_CDK_DEMO_VIZION_TOKEN = process.env.NEXT_PUBLIC_POLYGON_CDK_DEMO_VIZION_TOKEN?.trim() || "";
const POLYGON_CDK_DEMO_VIZION_HOST_ID = process.env.NEXT_PUBLIC_POLYGON_CDK_DEMO_VIZION_HOST_ID?.trim() || "";

export {
  DEFAULT_POLYGON_CDK_DEMO_SERVICE_ID,
  POLYGON_CDK_DEMO_SERVICE_ID,
  POLYGON_CDK_DEMO_VIZION_TOKEN,
  POLYGON_CDK_DEMO_VIZION_HOST_ID,
};
