const DEFAULT_ZKSYNC_DEMO_SERVICE_ID = "d0d0c1d1-8899-48b3-93f8-6fb8b9e5c010";

const ZKSYNC_DEMO_SERVICE_ID = process.env.NEXT_PUBLIC_ZKSYNC_DEMO_SERVICE_ID?.trim() || DEFAULT_ZKSYNC_DEMO_SERVICE_ID;

const ZKSYNC_DEMO_VIZION_TOKEN = process.env.NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_TOKEN?.trim() || "";
const ZKSYNC_DEMO_VIZION_HOST_ID = process.env.NEXT_PUBLIC_ZKSYNC_DEMO_VIZION_HOST_ID?.trim() || "11859";

export { DEFAULT_ZKSYNC_DEMO_SERVICE_ID, ZKSYNC_DEMO_SERVICE_ID, ZKSYNC_DEMO_VIZION_TOKEN, ZKSYNC_DEMO_VIZION_HOST_ID };
